DWAPlannerROS:
  # Velocity limits. NOTE: tuning
  max_vel_x: 0.4
  min_vel_x: -0.4
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_trans:  0.4
  min_vel_trans:  0.04  # Min ~0.02m/s
  max_vel_theta: 1.8  # 1.54 for 0.4m/s  
  min_vel_theta: 0.07    # Min ~0.02m/s

  # Acceleration limits. NOTE: tuning
  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 10.0

  # Goal Tolerance Parametes. NOTE: tuning
  xy_goal_tolerance: 0.15         # default: 0.10
  yaw_goal_tolerance: 0.3         # default: 0.05
  latch_xy_goal_tolerance: false  # default: false

  # Forward Simulation Parameters. NOTE: tuning
  sim_time: 1.3             # default: 1.7
  sim_granularity: 0.025    # default: 0.025
  vx_samples: 10            # default: 3
  vy_samples: 0             # default: 10
  vth_samples: 20           # default: 20    

  # Trajectory Scoring Parameters
  # cost =
  # path_distance_bias * (distance to path from the endpoint of the trajectory in meters)
  # + goal_distance_bias * (distance to local goal from the endpoint of the trajectory in meters)
  # + occdist_scale * (maximum obstacle cost along the trajectory in obstacle cost (0-254))
  meter_scoring: true           # default: false
  path_distance_bias: 32.0      # default: 32.0  Reduce to allow tp diverge from the global plan
  goal_distance_bias: 20.0      # default: 24.0
  occdist_scale: 0.01           # default: 0.01
  forward_point_distance: 0.0 # default: 0.325  Cost value for robot alignment to the path
  stop_time_buffer: 0.2         # default: 0.2
  scaling_speed: 0.2            # default: 0.25
  max_scaling_factor: 0.2       # default: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

  # Debugging
  publish_traj_pc : false      # default: false
  publish_cost_grid_pc: false  # default: false Not working? just white dots

# TrajectoryPlannerROS:
#   max_vel_x: 0.55
#   min_vel_x: -0.2

#   max_vel_theta:  1.0
#   min_vel_theta: -1.0
#   min_in_place_vel_theta: 1.0

#   acc_lim_x: 0.7
#   acc_lim_y: 0.0
#   acc_lim_theta: 1.0

# # Goal Tolerance Parameters
#   meter_scoring: true
#   xy_goal_tolerance: 0.20
#   yaw_goal_tolerance: 0.5

# # Differential-drive robot configuration
#   holonomic_robot: false

# # Forward Simulation Parameters
#   sim_time: 1.0
#   vx_samples: 15
#   vtheta_samples: 20
#   sim_granularity: 0.025

