TrajectoryPlannerROS:
  min_vel_x: 0.1
  max_vel_x: 0.3
  min_vel_theta: -0.6
  max_vel_theta: 0.6
  min_in_place_vel_theta: 0.3

  acc_lim_theta: 0.3
  acc_lim_x: 0.2
  acc_lim_y: 0.2

  holonomic_robot: false