local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0  
  publish_frequency: 0.5  # Visualization frequency
  rolling_window: true
  width: 4.994
  height: 4.994
  resolution: 0.025  # Can be different than static map

  inflation_radius: 2.0
  cost_scaling_factor: 2.0

  plugins:
    - {name: sonar_layer,   type: "range_sensor_layer::RangeSensorLayer"}
    - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
