footprint: [[0.14, -0.0625], [0.09, -0.0625], [0.09, -0.3], [-0.07, -0.3], [-0.07, -0.235], [-0.32, -0.235], [-0.47, 0], [-0.32, 0.235], [-0.07, 0.235], [-0.07, 0.3], [0.09, 0.3], [0.09, 0.0625], [0.14, 0.0625]]
footprint_padding: 0.01
# robot_radius: 0.5

inflation_layer:
  inflation_radius: 0.45

sonar_layer:
  ns: ""
  frame: ultrasound
  # topics: ["/range_bump1", "/range_bump2"]
  # topics: ["/range_sonar"]
  topics: ["/range_sonar", "/range_bump1", "/range_bump2"]
  no_readings_timeout: 9999999.0  # Ignore timeout
  clear_threshold: 0.2
  mark_threshold: 0.9
  clear_on_max_reading: false