global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 2.0
  publish_frequency: 2.0  # Visualization frequency
  
  plugins:
      - {name: static_layer, type: 'costmap_2d::StaticLayer'}
      - {name: sonar_layer,   type: "range_sensor_layer::RangeSensorLayer"}
      - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}