local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0  
  publish_frequency: 5.0  # Visualization frequency # TODO: lower for event
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.025  # Can be different than static map
  # origin_x: -5.0
  # origin_y: -5.0

  plugins:
    - {name: sonar_layer,   type: "range_sensor_layer::RangeSensorLayer"}
    - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
