local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0  # Visualization frequency
  static_map: false
  rolling_window: true
  width: 15.0
  height: 15.0
  resolution: 0.05  # Can be different than static map

  plugins:
    - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}
    - {name: sonar_layer,   type: "range_sensor_layer::RangeSensorLayer"}