# Global planner
base_global_planner: "navfn/NavfnROS"
# base_global_planner: "SBPLLatticePlanner"

# Local planner
base_local_planner: "dwa_local_planner/DWAPlannerROS"
# base_local_planner: "base_local_planner/TrajectoryPlannerROS"
# base_local_planner: "pose_follower/PoseFollower"

# General
planner_frequency: 5.0
controller_frequency: 10.0
planner_patience: 5.0
controller_patience: 15.0
oscillation_timeout: 5.0
oscillation_distance: 0.2
shutdown_costmaps: false

# Recovery behaviours
recovery_behavior_enabled: true
clearing_rotation_allowed: false
# max_planning_retries: 2


recovery_behaviors:
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset2'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

conservative_reset:
  reset_distance: 0.5
  layer_names: ['sonar_layer']
  
  aggressive_reset:
    reset_distance: 0.0
    layer_names: ['sonar_layer']

  aggressive_reset2:
    reset_distance: 0.0
    layer_names: ['sonar_layer']
