planner_frequency: 1.0

# conservative_reset:
#   reset_distance: 5.55
#   layer_names: ['sonar_layer', 'inflation_layer']

recovery_behavior_enabled: true

recovery_behaviors:
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'costmap_reset_conservative'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

aggressive_reset:
  reset_distance: 0.0
  layer_names: ['sonar_layer', 'inflation_layer']


base_global_planner: 'SBPLLatticePlanner'

costmap_reset_conservative:
  reset_distance: 1.5
  layer_names: ['sonar_layer', 'inflation_layer']