# Global planner
# base_global_planner: "navfn/NavfnROS"
base_global_planner: "global_planner/GlobalPlanner"
# base_global_planner: "SBPLLatticePlanner"

# Local planner
base_local_planner: "dwa_local_planner/DWAPlannerROS"
# base_local_planner: "base_local_planner/TrajectoryPlannerROS"
# base_local_planner: "pose_follower/PoseFollower"

# General
planner_frequency: 0.33     # Global planner default: 0.0  if 0 run on new goal or when local planner is blocked
controller_frequency: 15.0  # Local planner  default: 20.0
planner_patience: 8.0       # How long to wait before clearing default: 5.0
controller_patience: 8.0    # default: 15.0
oscillation_timeout: 5.0    # default: 0.0
oscillation_distance: 0.4   # default: 0.5
shutdown_costmaps: false    # default: false
max_planning_retries: -1    # default: -1

# Recovery behaviours
recovery_behavior_enabled: true  # Also has custom recovery in follow_waypoints
clearing_rotation_allowed: false
# max_planning_retries: 2


recovery_behaviors:
  # - name: 'conservative_reset'
  #   type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

# conservative_reset:
#   reset_distance: 0.5
#   layer_names: ['sonar_layer']

aggressive_reset:
  reset_distance: 0.0
  layer_names: ['sonar_layer']
