(cl:in-package samana_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          QUATERNION_X-VAL
          QUATERNION_X
          QUATERNION_Y-VAL
          QUATERNION_Y
          QUATERNION_Z-VAL
          QUATERNION_Z
          QUATERNION_W-VAL
          QUATERNION_W
          LINEAR_ACCELERATION_X-VAL
          LINEAR_ACCELERATION_X
          LINEAR_ACCELERATION_Y-VAL
          LINEAR_ACCELERATION_Y
          LINEAR_ACCELERATION_Z-VAL
          LINEAR_ACCELERATION_Z
          ANGULAR_VELOCITY_X-VAL
          ANGULAR_VELOCITY_X
          ANGULAR_VELOCITY_Y-VAL
          ANGULAR_VELOCITY_Y
          ANGULAR_VELOCITY_Z-VAL
          ANGULAR_VELOCITY_Z
))