# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from samana_msgs/ArmData.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ArmData(genpy.Message):
  _md5sum = "3812456ac8efcba0c0c24a88991ba799"
  _type = "samana_msgs/ArmData"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int16 current_grabber
int16 current_lifter
uint8 limit_switches
"""
  __slots__ = ['current_grabber','current_lifter','limit_switches']
  _slot_types = ['int16','int16','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       current_grabber,current_lifter,limit_switches

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ArmData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.current_grabber is None:
        self.current_grabber = 0
      if self.current_lifter is None:
        self.current_lifter = 0
      if self.limit_switches is None:
        self.limit_switches = 0
    else:
      self.current_grabber = 0
      self.current_lifter = 0
      self.limit_switches = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2hB().pack(_x.current_grabber, _x.current_lifter, _x.limit_switches))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.current_grabber, _x.current_lifter, _x.limit_switches,) = _get_struct_2hB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2hB().pack(_x.current_grabber, _x.current_lifter, _x.limit_switches))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.current_grabber, _x.current_lifter, _x.limit_switches,) = _get_struct_2hB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2hB = None
def _get_struct_2hB():
    global _struct_2hB
    if _struct_2hB is None:
        _struct_2hB = struct.Struct("<2hB")
    return _struct_2hB
