# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from samana_msgs/ImuSmall.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class ImuSmall(genpy.Message):
  _md5sum = "c052128fb9568718800fa0ba7071e271"
  _type = "samana_msgs/ImuSmall"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
float32 quaternion_x
float32 quaternion_y
float32 quaternion_z
float32 quaternion_w
float32 linear_acceleration_x
float32 linear_acceleration_y
float32 linear_acceleration_z
float32 angular_velocity_x
float32 angular_velocity_y
float32 angular_velocity_z
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','quaternion_x','quaternion_y','quaternion_z','quaternion_w','linear_acceleration_x','linear_acceleration_y','linear_acceleration_z','angular_velocity_x','angular_velocity_y','angular_velocity_z']
  _slot_types = ['std_msgs/Header','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,quaternion_x,quaternion_y,quaternion_z,quaternion_w,linear_acceleration_x,linear_acceleration_y,linear_acceleration_z,angular_velocity_x,angular_velocity_y,angular_velocity_z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ImuSmall, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.quaternion_x is None:
        self.quaternion_x = 0.
      if self.quaternion_y is None:
        self.quaternion_y = 0.
      if self.quaternion_z is None:
        self.quaternion_z = 0.
      if self.quaternion_w is None:
        self.quaternion_w = 0.
      if self.linear_acceleration_x is None:
        self.linear_acceleration_x = 0.
      if self.linear_acceleration_y is None:
        self.linear_acceleration_y = 0.
      if self.linear_acceleration_z is None:
        self.linear_acceleration_z = 0.
      if self.angular_velocity_x is None:
        self.angular_velocity_x = 0.
      if self.angular_velocity_y is None:
        self.angular_velocity_y = 0.
      if self.angular_velocity_z is None:
        self.angular_velocity_z = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.quaternion_x = 0.
      self.quaternion_y = 0.
      self.quaternion_z = 0.
      self.quaternion_w = 0.
      self.linear_acceleration_x = 0.
      self.linear_acceleration_y = 0.
      self.linear_acceleration_z = 0.
      self.angular_velocity_x = 0.
      self.angular_velocity_y = 0.
      self.angular_velocity_z = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_10f().pack(_x.quaternion_x, _x.quaternion_y, _x.quaternion_z, _x.quaternion_w, _x.linear_acceleration_x, _x.linear_acceleration_y, _x.linear_acceleration_z, _x.angular_velocity_x, _x.angular_velocity_y, _x.angular_velocity_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.quaternion_x, _x.quaternion_y, _x.quaternion_z, _x.quaternion_w, _x.linear_acceleration_x, _x.linear_acceleration_y, _x.linear_acceleration_z, _x.angular_velocity_x, _x.angular_velocity_y, _x.angular_velocity_z,) = _get_struct_10f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_10f().pack(_x.quaternion_x, _x.quaternion_y, _x.quaternion_z, _x.quaternion_w, _x.linear_acceleration_x, _x.linear_acceleration_y, _x.linear_acceleration_z, _x.angular_velocity_x, _x.angular_velocity_y, _x.angular_velocity_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.quaternion_x, _x.quaternion_y, _x.quaternion_z, _x.quaternion_w, _x.linear_acceleration_x, _x.linear_acceleration_y, _x.linear_acceleration_z, _x.angular_velocity_x, _x.angular_velocity_y, _x.angular_velocity_z,) = _get_struct_10f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_10f = None
def _get_struct_10f():
    global _struct_10f
    if _struct_10f is None:
        _struct_10f = struct.Struct("<10f")
    return _struct_10f
