# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from samana_msgs/ImuCalib.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ImuCalib(genpy.Message):
  _md5sum = "7764c0234b4e443d9ef754fa0119997d"
  _type = "samana_msgs/ImuCalib"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 sys
uint8 gyr
uint8 acc
uint8 mag
int8 temp"""
  __slots__ = ['sys','gyr','acc','mag','temp']
  _slot_types = ['uint8','uint8','uint8','uint8','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sys,gyr,acc,mag,temp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ImuCalib, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.sys is None:
        self.sys = 0
      if self.gyr is None:
        self.gyr = 0
      if self.acc is None:
        self.acc = 0
      if self.mag is None:
        self.mag = 0
      if self.temp is None:
        self.temp = 0
    else:
      self.sys = 0
      self.gyr = 0
      self.acc = 0
      self.mag = 0
      self.temp = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4Bb().pack(_x.sys, _x.gyr, _x.acc, _x.mag, _x.temp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.sys, _x.gyr, _x.acc, _x.mag, _x.temp,) = _get_struct_4Bb().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4Bb().pack(_x.sys, _x.gyr, _x.acc, _x.mag, _x.temp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.sys, _x.gyr, _x.acc, _x.mag, _x.temp,) = _get_struct_4Bb().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4Bb = None
def _get_struct_4Bb():
    global _struct_4Bb
    if _struct_4Bb is None:
        _struct_4Bb = struct.Struct("<4Bb")
    return _struct_4Bb
