# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from samana_msgs/RCModes.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RCModes(genpy.Message):
  _md5sum = "f93b20a9c6f7b0344addef9c5a6daf0f"
  _type = "samana_msgs/RCModes"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool allow_rc
bool armed
bool auton_mode
uint8 arm_mode"""
  __slots__ = ['allow_rc','armed','auton_mode','arm_mode']
  _slot_types = ['bool','bool','bool','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       allow_rc,armed,auton_mode,arm_mode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RCModes, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.allow_rc is None:
        self.allow_rc = False
      if self.armed is None:
        self.armed = False
      if self.auton_mode is None:
        self.auton_mode = False
      if self.arm_mode is None:
        self.arm_mode = 0
    else:
      self.allow_rc = False
      self.armed = False
      self.auton_mode = False
      self.arm_mode = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.allow_rc, _x.armed, _x.auton_mode, _x.arm_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.allow_rc, _x.armed, _x.auton_mode, _x.arm_mode,) = _get_struct_4B().unpack(str[start:end])
      self.allow_rc = bool(self.allow_rc)
      self.armed = bool(self.armed)
      self.auton_mode = bool(self.auton_mode)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.allow_rc, _x.armed, _x.auton_mode, _x.arm_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.allow_rc, _x.armed, _x.auton_mode, _x.arm_mode,) = _get_struct_4B().unpack(str[start:end])
      self.allow_rc = bool(self.allow_rc)
      self.armed = bool(self.armed)
      self.auton_mode = bool(self.auton_mode)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4B = None
def _get_struct_4B():
    global _struct_4B
    if _struct_4B is None:
        _struct_4B = struct.Struct("<4B")
    return _struct_4B
