// Generated by gencpp from file samana_msgs/Bump.msg
// DO NOT EDIT!


#ifndef SAMANA_MSGS_MESSAGE_BUMP_H
#define SAMANA_MSGS_MESSAGE_BUMP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace samana_msgs
{
template <class ContainerAllocator>
struct Bump_
{
  typedef Bump_<ContainerAllocator> Type;

  Bump_()
    : header()
    , bump_bits(0)  {
    }
  Bump_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , bump_bits(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _bump_bits_type;
  _bump_bits_type bump_bits;





  typedef boost::shared_ptr< ::samana_msgs::Bump_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::samana_msgs::Bump_<ContainerAllocator> const> ConstPtr;

}; // struct Bump_

typedef ::samana_msgs::Bump_<std::allocator<void> > Bump;

typedef boost::shared_ptr< ::samana_msgs::Bump > BumpPtr;
typedef boost::shared_ptr< ::samana_msgs::Bump const> BumpConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::samana_msgs::Bump_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::samana_msgs::Bump_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace samana_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'samana_msgs': ['/home/combinacijus/Documents/SamanaAutonomousRobot/ROS/samana_ws/src/samana_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::samana_msgs::Bump_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::samana_msgs::Bump_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::samana_msgs::Bump_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::samana_msgs::Bump_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::samana_msgs::Bump_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::samana_msgs::Bump_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::samana_msgs::Bump_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be760e4b4932adb10f1e9fc66f2d1769";
  }

  static const char* value(const ::samana_msgs::Bump_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe760e4b4932adb1ULL;
  static const uint64_t static_value2 = 0x0f1e9fc66f2d1769ULL;
};

template<class ContainerAllocator>
struct DataType< ::samana_msgs::Bump_<ContainerAllocator> >
{
  static const char* value()
  {
    return "samana_msgs/Bump";
  }

  static const char* value(const ::samana_msgs::Bump_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::samana_msgs::Bump_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint16 bump_bits\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::samana_msgs::Bump_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::samana_msgs::Bump_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.bump_bits);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Bump_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::samana_msgs::Bump_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::samana_msgs::Bump_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "bump_bits: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.bump_bits);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAMANA_MSGS_MESSAGE_BUMP_H
