// Generated by gencpp from file samana_msgs/OdometrySmall.msg
// DO NOT EDIT!


#ifndef SAMANA_MSGS_MESSAGE_ODOMETRYSMALL_H
#define SAMANA_MSGS_MESSAGE_ODOMETRYSMALL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace samana_msgs
{
template <class ContainerAllocator>
struct OdometrySmall_
{
  typedef OdometrySmall_<ContainerAllocator> Type;

  OdometrySmall_()
    : header()
    , delta_ticks1(0)
    , delta_ticks2(0)
    , rps1(0.0)
    , rps2(0.0)
    , dt(0)  {
    }
  OdometrySmall_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , delta_ticks1(0)
    , delta_ticks2(0)
    , rps1(0.0)
    , rps2(0.0)
    , dt(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _delta_ticks1_type;
  _delta_ticks1_type delta_ticks1;

   typedef int16_t _delta_ticks2_type;
  _delta_ticks2_type delta_ticks2;

   typedef float _rps1_type;
  _rps1_type rps1;

   typedef float _rps2_type;
  _rps2_type rps2;

   typedef int16_t _dt_type;
  _dt_type dt;





  typedef boost::shared_ptr< ::samana_msgs::OdometrySmall_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::samana_msgs::OdometrySmall_<ContainerAllocator> const> ConstPtr;

}; // struct OdometrySmall_

typedef ::samana_msgs::OdometrySmall_<std::allocator<void> > OdometrySmall;

typedef boost::shared_ptr< ::samana_msgs::OdometrySmall > OdometrySmallPtr;
typedef boost::shared_ptr< ::samana_msgs::OdometrySmall const> OdometrySmallConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::samana_msgs::OdometrySmall_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::samana_msgs::OdometrySmall_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace samana_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'samana_msgs': ['/home/combinacijus/Documents/SamanaAutonomousRobot/ROS/samana_ws/src/samana_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::samana_msgs::OdometrySmall_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::samana_msgs::OdometrySmall_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::samana_msgs::OdometrySmall_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::samana_msgs::OdometrySmall_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::samana_msgs::OdometrySmall_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::samana_msgs::OdometrySmall_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::samana_msgs::OdometrySmall_<ContainerAllocator> >
{
  static const char* value()
  {
    return "98004b29be7f03ed0afbf8488b6e7875";
  }

  static const char* value(const ::samana_msgs::OdometrySmall_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x98004b29be7f03edULL;
  static const uint64_t static_value2 = 0x0afbf8488b6e7875ULL;
};

template<class ContainerAllocator>
struct DataType< ::samana_msgs::OdometrySmall_<ContainerAllocator> >
{
  static const char* value()
  {
    return "samana_msgs/OdometrySmall";
  }

  static const char* value(const ::samana_msgs::OdometrySmall_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::samana_msgs::OdometrySmall_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"int16 delta_ticks1\n"
"int16 delta_ticks2\n"
"float32 rps1\n"
"float32 rps2\n"
"int16 dt\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::samana_msgs::OdometrySmall_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::samana_msgs::OdometrySmall_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.delta_ticks1);
      stream.next(m.delta_ticks2);
      stream.next(m.rps1);
      stream.next(m.rps2);
      stream.next(m.dt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OdometrySmall_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::samana_msgs::OdometrySmall_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::samana_msgs::OdometrySmall_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "delta_ticks1: ";
    Printer<int16_t>::stream(s, indent + "  ", v.delta_ticks1);
    s << indent << "delta_ticks2: ";
    Printer<int16_t>::stream(s, indent + "  ", v.delta_ticks2);
    s << indent << "rps1: ";
    Printer<float>::stream(s, indent + "  ", v.rps1);
    s << indent << "rps2: ";
    Printer<float>::stream(s, indent + "  ", v.rps2);
    s << indent << "dt: ";
    Printer<int16_t>::stream(s, indent + "  ", v.dt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAMANA_MSGS_MESSAGE_ODOMETRYSMALL_H
