// Generated by gencpp from file samana_msgs/RCModes.msg
// DO NOT EDIT!


#ifndef SAMANA_MSGS_MESSAGE_RCMODES_H
#define SAMANA_MSGS_MESSAGE_RCMODES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace samana_msgs
{
template <class ContainerAllocator>
struct RCModes_
{
  typedef RCModes_<ContainerAllocator> Type;

  RCModes_()
    : allow_rc(false)
    , armed(false)
    , auton_mode(false)
    , arm_mode(0)  {
    }
  RCModes_(const ContainerAllocator& _alloc)
    : allow_rc(false)
    , armed(false)
    , auton_mode(false)
    , arm_mode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _allow_rc_type;
  _allow_rc_type allow_rc;

   typedef uint8_t _armed_type;
  _armed_type armed;

   typedef uint8_t _auton_mode_type;
  _auton_mode_type auton_mode;

   typedef uint8_t _arm_mode_type;
  _arm_mode_type arm_mode;





  typedef boost::shared_ptr< ::samana_msgs::RCModes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::samana_msgs::RCModes_<ContainerAllocator> const> ConstPtr;

}; // struct RCModes_

typedef ::samana_msgs::RCModes_<std::allocator<void> > RCModes;

typedef boost::shared_ptr< ::samana_msgs::RCModes > RCModesPtr;
typedef boost::shared_ptr< ::samana_msgs::RCModes const> RCModesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::samana_msgs::RCModes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::samana_msgs::RCModes_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace samana_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'samana_msgs': ['/home/combinacijus/Documents/SamanaAutonomousRobot/ROS/samana_ws/src/samana_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::samana_msgs::RCModes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::samana_msgs::RCModes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::samana_msgs::RCModes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::samana_msgs::RCModes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::samana_msgs::RCModes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::samana_msgs::RCModes_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::samana_msgs::RCModes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f93b20a9c6f7b0344addef9c5a6daf0f";
  }

  static const char* value(const ::samana_msgs::RCModes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf93b20a9c6f7b034ULL;
  static const uint64_t static_value2 = 0x4addef9c5a6daf0fULL;
};

template<class ContainerAllocator>
struct DataType< ::samana_msgs::RCModes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "samana_msgs/RCModes";
  }

  static const char* value(const ::samana_msgs::RCModes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::samana_msgs::RCModes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool allow_rc\n"
"bool armed\n"
"bool auton_mode\n"
"uint8 arm_mode\n"
;
  }

  static const char* value(const ::samana_msgs::RCModes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::samana_msgs::RCModes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.allow_rc);
      stream.next(m.armed);
      stream.next(m.auton_mode);
      stream.next(m.arm_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RCModes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::samana_msgs::RCModes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::samana_msgs::RCModes_<ContainerAllocator>& v)
  {
    s << indent << "allow_rc: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.allow_rc);
    s << indent << "armed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.armed);
    s << indent << "auton_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.auton_mode);
    s << indent << "arm_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.arm_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAMANA_MSGS_MESSAGE_RCMODES_H
