// Generated by gencpp from file samana_msgs/Sonic9.msg
// DO NOT EDIT!


#ifndef SAMANA_MSGS_MESSAGE_SONIC9_H
#define SAMANA_MSGS_MESSAGE_SONIC9_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace samana_msgs
{
template <class ContainerAllocator>
struct Sonic9_
{
  typedef Sonic9_<ContainerAllocator> Type;

  Sonic9_()
    : Header()
    , dist1(0)
    , dist2(0)
    , dist3(0)
    , dist4(0)
    , dist5(0)
    , dist6(0)
    , dist7(0)
    , dist8(0)
    , dist9(0)  {
    }
  Sonic9_(const ContainerAllocator& _alloc)
    : Header(_alloc)
    , dist1(0)
    , dist2(0)
    , dist3(0)
    , dist4(0)
    , dist5(0)
    , dist6(0)
    , dist7(0)
    , dist8(0)
    , dist9(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _Header_type;
  _Header_type Header;

   typedef int16_t _dist1_type;
  _dist1_type dist1;

   typedef int16_t _dist2_type;
  _dist2_type dist2;

   typedef int16_t _dist3_type;
  _dist3_type dist3;

   typedef int16_t _dist4_type;
  _dist4_type dist4;

   typedef int16_t _dist5_type;
  _dist5_type dist5;

   typedef int16_t _dist6_type;
  _dist6_type dist6;

   typedef int16_t _dist7_type;
  _dist7_type dist7;

   typedef int16_t _dist8_type;
  _dist8_type dist8;

   typedef int16_t _dist9_type;
  _dist9_type dist9;





  typedef boost::shared_ptr< ::samana_msgs::Sonic9_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::samana_msgs::Sonic9_<ContainerAllocator> const> ConstPtr;

}; // struct Sonic9_

typedef ::samana_msgs::Sonic9_<std::allocator<void> > Sonic9;

typedef boost::shared_ptr< ::samana_msgs::Sonic9 > Sonic9Ptr;
typedef boost::shared_ptr< ::samana_msgs::Sonic9 const> Sonic9ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::samana_msgs::Sonic9_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::samana_msgs::Sonic9_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace samana_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'samana_msgs': ['/home/combinacijus/Documents/ROS/samana_ws/src/samana_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::samana_msgs::Sonic9_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::samana_msgs::Sonic9_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::samana_msgs::Sonic9_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::samana_msgs::Sonic9_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::samana_msgs::Sonic9_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::samana_msgs::Sonic9_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::samana_msgs::Sonic9_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9475c4b12aca5b9b235ea1a9e9e22280";
  }

  static const char* value(const ::samana_msgs::Sonic9_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9475c4b12aca5b9bULL;
  static const uint64_t static_value2 = 0x235ea1a9e9e22280ULL;
};

template<class ContainerAllocator>
struct DataType< ::samana_msgs::Sonic9_<ContainerAllocator> >
{
  static const char* value()
  {
    return "samana_msgs/Sonic9";
  }

  static const char* value(const ::samana_msgs::Sonic9_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::samana_msgs::Sonic9_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header Header\n"
"int16 dist1\n"
"int16 dist2\n"
"int16 dist3\n"
"int16 dist4\n"
"int16 dist5\n"
"int16 dist6\n"
"int16 dist7\n"
"int16 dist8\n"
"int16 dist9\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::samana_msgs::Sonic9_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::samana_msgs::Sonic9_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Header);
      stream.next(m.dist1);
      stream.next(m.dist2);
      stream.next(m.dist3);
      stream.next(m.dist4);
      stream.next(m.dist5);
      stream.next(m.dist6);
      stream.next(m.dist7);
      stream.next(m.dist8);
      stream.next(m.dist9);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sonic9_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::samana_msgs::Sonic9_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::samana_msgs::Sonic9_<ContainerAllocator>& v)
  {
    s << indent << "Header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.Header);
    s << indent << "dist1: ";
    Printer<int16_t>::stream(s, indent + "  ", v.dist1);
    s << indent << "dist2: ";
    Printer<int16_t>::stream(s, indent + "  ", v.dist2);
    s << indent << "dist3: ";
    Printer<int16_t>::stream(s, indent + "  ", v.dist3);
    s << indent << "dist4: ";
    Printer<int16_t>::stream(s, indent + "  ", v.dist4);
    s << indent << "dist5: ";
    Printer<int16_t>::stream(s, indent + "  ", v.dist5);
    s << indent << "dist6: ";
    Printer<int16_t>::stream(s, indent + "  ", v.dist6);
    s << indent << "dist7: ";
    Printer<int16_t>::stream(s, indent + "  ", v.dist7);
    s << indent << "dist8: ";
    Printer<int16_t>::stream(s, indent + "  ", v.dist8);
    s << indent << "dist9: ";
    Printer<int16_t>::stream(s, indent + "  ", v.dist9);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAMANA_MSGS_MESSAGE_SONIC9_H
