// Generated by gencpp from file samana_msgs/Teleop.msg
// DO NOT EDIT!


#ifndef SAMANA_MSGS_MESSAGE_TELEOP_H
#define SAMANA_MSGS_MESSAGE_TELEOP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace samana_msgs
{
template <class ContainerAllocator>
struct Teleop_
{
  typedef Teleop_<ContainerAllocator> Type;

  Teleop_()
    : speed(0)
    , steer(0)  {
    }
  Teleop_(const ContainerAllocator& _alloc)
    : speed(0)
    , steer(0)  {
  (void)_alloc;
    }



   typedef int16_t _speed_type;
  _speed_type speed;

   typedef int16_t _steer_type;
  _steer_type steer;





  typedef boost::shared_ptr< ::samana_msgs::Teleop_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::samana_msgs::Teleop_<ContainerAllocator> const> ConstPtr;

}; // struct Teleop_

typedef ::samana_msgs::Teleop_<std::allocator<void> > Teleop;

typedef boost::shared_ptr< ::samana_msgs::Teleop > TeleopPtr;
typedef boost::shared_ptr< ::samana_msgs::Teleop const> TeleopConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::samana_msgs::Teleop_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::samana_msgs::Teleop_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace samana_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'samana_msgs': ['/home/combinacijus/Documents/SamanaAutonomousRobot/ROS/samana_ws/src/samana_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::samana_msgs::Teleop_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::samana_msgs::Teleop_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::samana_msgs::Teleop_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::samana_msgs::Teleop_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::samana_msgs::Teleop_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::samana_msgs::Teleop_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::samana_msgs::Teleop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8b9ad615ef7ce8cbee2931ec476027b";
  }

  static const char* value(const ::samana_msgs::Teleop_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8b9ad615ef7ce8cULL;
  static const uint64_t static_value2 = 0xbee2931ec476027bULL;
};

template<class ContainerAllocator>
struct DataType< ::samana_msgs::Teleop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "samana_msgs/Teleop";
  }

  static const char* value(const ::samana_msgs::Teleop_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::samana_msgs::Teleop_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 speed\n"
"int16 steer\n"
;
  }

  static const char* value(const ::samana_msgs::Teleop_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::samana_msgs::Teleop_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.steer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Teleop_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::samana_msgs::Teleop_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::samana_msgs::Teleop_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.speed);
    s << indent << "steer: ";
    Printer<int16_t>::stream(s, indent + "  ", v.steer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAMANA_MSGS_MESSAGE_TELEOP_H
