// Generated by gencpp from file samana_msgs/temp.msg
// DO NOT EDIT!


#ifndef SAMANA_MSGS_MESSAGE_TEMP_H
#define SAMANA_MSGS_MESSAGE_TEMP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace samana_msgs
{
template <class ContainerAllocator>
struct temp_
{
  typedef temp_<ContainerAllocator> Type;

  temp_()
    : temp(0.0)  {
    }
  temp_(const ContainerAllocator& _alloc)
    : temp(0.0)  {
  (void)_alloc;
    }



   typedef float _temp_type;
  _temp_type temp;





  typedef boost::shared_ptr< ::samana_msgs::temp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::samana_msgs::temp_<ContainerAllocator> const> ConstPtr;

}; // struct temp_

typedef ::samana_msgs::temp_<std::allocator<void> > temp;

typedef boost::shared_ptr< ::samana_msgs::temp > tempPtr;
typedef boost::shared_ptr< ::samana_msgs::temp const> tempConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::samana_msgs::temp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::samana_msgs::temp_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace samana_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'samana_msgs': ['/home/combinacijus/Documents/ROS/samana_ws/src/samana_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::samana_msgs::temp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::samana_msgs::temp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::samana_msgs::temp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::samana_msgs::temp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::samana_msgs::temp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::samana_msgs::temp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::samana_msgs::temp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b8b64af59df1604df7e647a04e645a45";
  }

  static const char* value(const ::samana_msgs::temp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb8b64af59df1604dULL;
  static const uint64_t static_value2 = 0xf7e647a04e645a45ULL;
};

template<class ContainerAllocator>
struct DataType< ::samana_msgs::temp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "samana_msgs/temp";
  }

  static const char* value(const ::samana_msgs::temp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::samana_msgs::temp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 temp\n"
;
  }

  static const char* value(const ::samana_msgs::temp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::samana_msgs::temp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.temp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct temp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::samana_msgs::temp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::samana_msgs::temp_<ContainerAllocator>& v)
  {
    s << indent << "temp: ";
    Printer<float>::stream(s, indent + "  ", v.temp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAMANA_MSGS_MESSAGE_TEMP_H
